---
sonarr_enabled: false
sonarr_available_externally: false

# directories
sonarr_data_directory: "{{ docker_home }}/sonarr/config"
sonarr_tv_directory: "{{ tv_root }}"
sonarr_kidtv_directory: "{{ kidtv_root }}"
sonarr_download_directory: "{{ downloads_root }}"

# uid / gid
sonarr_user_id: "0"
sonarr_group_id: "0"

# network
sonarr_port: "8989"
sonarr_hostname: "sonarr"

# docker
sonarr_container_name: "sonarr"
sonarr_image_name: "linuxserver/sonarr"
sonarr_image_version: "4.0.15.2941-ls293"

# specs
sonarr_memory: 1g
